version: "3"
services:
  slidev:
    build: .
    tty: true
    volumes:
      - ./slidev:/root/slidev
    ports:
      - 3030:3030
    working_dir: /root/slidev/slidev
    command: npx slidev --remote